all: 
	g++ -o zelda -lclanCore -lclanDisplay -lclanApp -lclanSound -lm *.cpp
	mv zelda ..
                                                                                
clean:
	-rm -rf *.o
	-rm simple

