//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 6:08:42 AM on Friday, November 16, 2001
//
//	Generated for file: C:\ldsmith\gatech\cs4750\test\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"RGA"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSearchButton                          1028	//(Left Origin = 9, Top Origin = 145, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUnnamed1007BitMap                     1235	//(Left Origin = 0, Top Origin = 16, Bitmap Resource ID = 1235, Usable = 1)
#define MainUnnamed1008BitMap                     1236	//(Left Origin = 96, Top Origin = 16, Bitmap Resource ID = 1236, Usable = 1)
#define MainNameField                             1001	//(Left Origin = 40, Top Origin = 48, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainPriceFromField                        1022	//(Left Origin = 56, Top Origin = 80, Width = 15, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainPriceToField                          1023	//(Left Origin = 104, Top Origin = 80, Width = 15, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCityField                             1024	//(Left Origin = 40, Top Origin = 96, Width = 40, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTimeFromField                         1026	//(Left Origin = 40, Top Origin = 112, Width = 15, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTimeToField                           1027	//(Left Origin = 96, Top Origin = 112, Width = 15, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1009Label                      1009	//(Left Origin = 8, Top Origin = 48, Usable = 1, Font = Standard)
#define MainUnnamed1010Label                      1010	//(Left Origin = 8, Top Origin = 64, Usable = 1, Font = Standard)
#define MainUnnamed1012Label                      1012	//(Left Origin = 8, Top Origin = 80, Usable = 1, Font = Standard)
#define MainUnnamed1013Label                      1013	//(Left Origin = 8, Top Origin = 96, Usable = 1, Font = Standard)
#define MainUnnamed1014Label                      1014	//(Left Origin = 8, Top Origin = 112, Usable = 1, Font = Standard)
#define MainUnnamed1015Label                      1015	//(Left Origin = 8, Top Origin = 128, Usable = 1, Font = Standard)
#define MainUnnamed1020Label                      1020	//(Left Origin = 40, Top Origin = 80, Usable = 1, Font = Standard)
#define MainUnnamed1021Label                      1021	//(Left Origin = 80, Top Origin = 80, Usable = 1, Font = Standard)
#define MainUnnamed1025Label                      1025	//(Left Origin = 88, Top Origin = 96, Usable = 1, Font = Standard)
#define MainUnnamed1002List                       1002	//(Left Origin = 48, Top Origin = 80, Width = 60, Usable = 0, Font = Standard, Visible Items = 5)
#define MainUnnamed1003List                       1003	//(Left Origin = 48, Top Origin = 120, Width = 40, Usable = 0, Font = Standard, Visible Items = 2)
#define MainUnnamed1004List                       1004	//(Left Origin = 112, Top Origin = 120, Width = 40, Usable = 0, Font = Standard, Visible Items = 2)
#define MainUnnamed1005List                       1005	//(Left Origin = 120, Top Origin = 104, Width = 40, Usable = 0, Font = Standard, Visible Items = 5)
#define MainUnnamed1006List                       1006	//(Left Origin = 96, Top Origin = 120, Width = 60, Usable = 0, Font = Standard, Visible Items = 4)
#define MainCuisinePopTrigger                     1011	//(Left Origin = 40, Top Origin = 64, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1002)
#define MainTimeFromPopTrigger                    1016	//(Left Origin = 64, Top Origin = 112, Width = 30, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1003)
#define MainTimeToPopTrigger                      1017	//(Left Origin = 112, Top Origin = 112, Width = 30, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1004)
#define MainPaymentsAcceptedPopTrigger            1018	//(Left Origin = 96, Top Origin = 128, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1006)
#define MainStatePopTrigger                       1019	//(Left Origin = 115, Top Origin = 96, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1005)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 30, Top Origin = 14, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 14, Top Origin = 30, Usable = 1, Font = Standard)


//	Resource: tFRM 1200
#define ResultsForm                               1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ResultsSearchButton                       1202	//(Left Origin = 17, Top Origin = 137, Width = 62, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ResultsDetailsButton                      1204	//(Left Origin = 100, Top Origin = 41, Width = 58, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ResultsDirectionsButton                   1205	//(Left Origin = 100, Top Origin = 57, Width = 58, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ResultsPlaceOrderButton                   1206	//(Left Origin = 100, Top Origin = 105, Width = 58, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ResultsMenuButton                         1207	//(Left Origin = 100, Top Origin = 73, Width = 58, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ResultsWaitTimeButton                     1208	//(Left Origin = 100, Top Origin = 89, Width = 58, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ResultsUnnamed1201Label                   1201	//(Left Origin = 40, Top Origin = 16, Usable = 1, Font = Standard)
#define ResultsResultsList                        1203	//(Left Origin = 8, Top Origin = 40, Width = 88, Usable = 1, Font = Standard, Visible Items = 7)


//	Resource: tFRM 1300
#define DetailsForm                               1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DetailsBackButton                         1302	//(Left Origin = 17, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DetailsNameLabel                          1301	//(Left Origin = 48, Top Origin = 24, Usable = 1, Font = Standard)
#define DetailsUnnamed1303Label                   1303	//(Left Origin = 8, Top Origin = 40, Usable = 1, Font = Standard)
#define DetailsPhoneLabel                         1304	//(Left Origin = 56, Top Origin = 40, Usable = 1, Font = Standard)
#define DetailsUnnamed1305Label                   1305	//(Left Origin = 8, Top Origin = 56, Usable = 1, Font = Standard)
#define DetailsAddressLabel                       1306	//(Left Origin = 56, Top Origin = 56, Usable = 1, Font = Standard)
#define DetailsCityLabel                          1307	//(Left Origin = 56, Top Origin = 72, Usable = 1, Font = Standard)
#define DetailsStateLabel                         1308	//(Left Origin = 112, Top Origin = 72, Usable = 1, Font = Standard)
#define DetailsUnnamed1309Label                   1309	//(Left Origin = 8, Top Origin = 88, Usable = 1, Font = Standard)
#define DetailsUnnamed1310Label                   1310	//(Left Origin = 8, Top Origin = 24, Usable = 1, Font = Standard)
#define DetailsUnnamed1311Label                   1311	//(Left Origin = 8, Top Origin = 104, Usable = 1, Font = Standard)
#define DetailsUnnamed1312Label                   1312	//(Left Origin = 8, Top Origin = 120, Usable = 1, Font = Standard)
#define DetailsPriceRangeLabel                    1313	//(Left Origin = 72, Top Origin = 88, Usable = 1, Font = Standard)
#define DetailsPaymentsAcceptedLabel              1314	//(Left Origin = 104, Top Origin = 104, Usable = 1, Font = Standard)
#define DetailsHoursLabel                         1315	//(Left Origin = 48, Top Origin = 120, Usable = 1, Font = Standard)
#define DetailsName2Label                         1316	//(Left Origin = 8, Top Origin = 8, Usable = 1, Font = Bold)
#define DetailsCuisine2Label                      1317	//(Left Origin = 88, Top Origin = 136, Usable = 1, Font = Standard)


//	Resource: tFRM 1400
#define DirectionsForm                            1400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DirectionsBackButton                      1402	//(Left Origin = 17, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DirectionsUnnamed1401BitMap               1237	//(Left Origin = 0, Top Origin = 0, Bitmap Resource ID = 1237, Usable = 1)
#define DirectionsUnnamed1403Label                1403	//(Left Origin = 76, Top Origin = 112, Usable = 1, Font = Standard)


//	Resource: tFRM 1500
#define MenuForm                                  1500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MenuBackButton                            1502	//(Left Origin = 17, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MenuNameLabel                             1503	//(Left Origin = 8, Top Origin = 8, Usable = 1, Font = Bold)
#define MenuUnnamed1501List                       1501	//(Left Origin = 2, Top Origin = 25, Width = 156, Usable = 1, Font = Standard, Visible Items = 8)


//	Resource: tFRM 1600
#define WaitTimeForm                              1600	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define WaitTimeMakeReservationsButton            1602	//(Left Origin = 17, Top Origin = 113, Width = 86, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WaitTimeBackButton                        1603	//(Left Origin = 17, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WaitTimeRestaurantLabel                   1601	//(Left Origin = 8, Top Origin = 8, Usable = 1, Font = Standard)
#define WaitTimeMinutesLabel                      1604	//(Left Origin = 8, Top Origin = 24, Usable = 1, Font = Standard)


//	Resource: tFRM 1700
#define PlaceOrderForm                            1700	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define PlaceOrderBackButton                      1701	//(Left Origin = 9, Top Origin = 145, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PlaceOrderOrderButton                     1702	//(Left Origin = 113, Top Origin = 97, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PlaceOrderUnnamed1705Button               1705	//(Left Origin = 9, Top Origin = 97, Width = 92, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PlaceOrderUnnamed1706Button               1706	//(Left Origin = 9, Top Origin = 113, Width = 92, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PlaceOrderUnnamed1703Label                1703	//(Left Origin = 8, Top Origin = 0, Usable = 1, Font = Standard)
#define PlaceOrderUnnamed1704List                 1704	//(Left Origin = 2, Top Origin = 16, Width = 152, Usable = 1, Font = Standard, Visible Items = 6)


//	Resource: tFRM 1800
#define XXXXXForm                                 128	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define XXXXXReserveButton                        184	//(Left Origin = 9, Top Origin = 137, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define XXXXXBackButton                           185	//(Left Origin = 73, Top Origin = 137, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define XXXXXUnnamed130Field                      130	//(Left Origin = 88, Top Origin = 24, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define XXXXXUnnamed132Field                      132	//(Left Origin = 88, Top Origin = 40, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define XXXXXUnnamed134Field                      134	//(Left Origin = 72, Top Origin = 56, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define XXXXXUnnamed181Label                      181	//(Left Origin = 8, Top Origin = 24, Usable = 1, Font = Standard)
#define XXXXXUnnamed182Label                      182	//(Left Origin = 8, Top Origin = 40, Usable = 1, Font = Standard)
#define XXXXXUnnamed183Label                      183	//(Left Origin = 8, Top Origin = 56, Usable = 1, Font = Standard)


//	Resource: tFRM 1900
#define MakeReservationForm                       1900	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MakeReservationBackButton                 1907	//(Left Origin = 9, Top Origin = 137, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MakeReservationRequestButton              1908	//(Left Origin = 17, Top Origin = 73, Width = 48, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MakeReservationUnnamed1909BitMap          1238	//(Left Origin = 88, Top Origin = 72, Bitmap Resource ID = 1238, Usable = 1)
#define MakeReservationUnnamed1904Field           1904	//(Left Origin = 80, Top Origin = 16, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MakeReservationUnnamed1905Field           1905	//(Left Origin = 104, Top Origin = 32, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MakeReservationUnnamed1906Field           1906	//(Left Origin = 96, Top Origin = 48, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MakeReservationUnnamed1901Label           1901	//(Left Origin = 16, Top Origin = 16, Usable = 1, Font = Standard)
#define MakeReservationUnnamed1902Label           1902	//(Left Origin = 16, Top Origin = 32, Usable = 1, Font = Standard)
#define MakeReservationUnnamed1903Label           1903	//(Left Origin = 16, Top Origin = 48, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000

//	Resource: PICT 1000
#define foodBitmap                                1000
//	Resource: PICT 42
#define BitmapID42Bitmap                          42
//	Resource: PICT 43
#define BitmapID43Bitmap                          43
//	Resource: PICT 44
#define BitmapID44Bitmap                          44
//	Resource: PICT 45
#define SearchBitmap                              45
//	Resource: PICT 46
#define Search2Bitmap                             46
//	Resource: PICT 47
#define mapBitmap                                 47
//	Resource: PICT 147
#define map2Bitmap                                147
//	Resource: PICT 148
#define tableBitmap                               148
//	Resource: tbmf 1237
#define MapBitmapFamily                           1237

//	Resource: tbmf 1234
#define BitmapResourceID1234BitmapFamily          1234

//	Resource: tbmf 1235
#define SearchBitmapFamily                        1235

//	Resource: tbmf 1236
#define Search2BitmapFamily                       1236

//	Resource: tbmf 1238
#define TableBitmapFamily                         1238
