# Simple Makefile for g++ 
# ----------------------
# Replace Class1 and Class2 with your classes below.
# If you add a new class C, you must add C.o to the OBJS definition
# and add a dependency for the .h file like:
#	C.o: C.h

CCC=g++
EXE=oob

# add -Wall for LOTS of warnings, -g for debugger support
CCFLAGS = -g -Wall -Woverloaded-virtual 

OBJS = Bank.o Customer.o Account.o SavingAccount.o MoneyMarketAccount.o CheckingAccount.o 

# suffix rule to tell SGI make how to compile C++ programs
.SUFFIXES: .cc
# second line below must begin with a single TAB character!
.cc.o: 
	$(CCC) $(CCFLAGS) -c $<

# second line below must begin with a single TAB character!
oob: $(OBJS)
	$(CCC) -o $(EXE) $(OBJS)

Bank.o: Bank.h
Customer.o: Customer.h
Account.o: Account.h
SavingAccount.o: SavingAccount.h
CheckingAccount.o: CheckingAccount.h
MoneyMarketAccount.o: MoneyMarketAccount.h

# second line below must begin with a single TAB character!
clean:
	-rm -rf *.o core $(EXE)
